PUT http://127.0.0.1:3003/api/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MDcxMjIwMDd9.p-5Mwul2xMC458n1Ws3VJuBCvLnbbOe0LCl8HuDIzVI

{
    "unread": false
}